### ISSUE TITLE
Legend control in ipyleaflet

### ISSUE THREAD

**Issue by martinRenou** [weatherforce/ipyleaflet-legend#5]
Although it's already possible to make a legend in ipyleaflet using the `HTML` widget in a `WidgetControl`, I would not be against putting this in ipyleaflet by default.

If you would consider opening a PR adding this as a `LegendControl` in ipyleaflet, I would be super happy to merge it :)

**Comment by TomTom4** [comment]
Hey @martinRenou, thank you very much for the proposal, I will definetly open a PR ! :) 
Also I have made an other piece of code, which is a basic button that reset the Map to initial zoom and center location. Just published it here: https://github.com/weatherforce/ipyleaflet-reset. If you are interested to add it to ipyleaflet, tell me and I would be very happy to do it ! :D

**Comment by TomTom4** [comment]
Merged in ipyleaflet :grin:
